export type INITIALIZE_FOODS = "FOODS/INITIALIZE_FOODS"
export const INITIALIZE_FOODS: INITIALIZE_FOODS = "FOODS/INITIALIZE_FOODS";

export type GET_FOODS = "FOODS/GET_FOODS";
export const GET_FOODS: GET_FOODS = "FOODS/GET_FOODS";

export type UPDATE_FILTER = "FOODS/UPDATE_FILTER";
export const UPDATE_FILTER: UPDATE_FILTER = "FOODS/UPDATE_FILTER";